#!/bin/bash

# Step 1: Build Docker Image
docker build -t Amharic_DBpedia_Chapter .

# Step 2: Run Container
container_id=$(docker run -d my-angular-app)

# Step 3: Extract Files
docker cp $container_id:/app/docs/dist/Amharic_DBpedia_Chapter ./dist

# Step 4: Stop and Remove Container
docker rm -f $container_id

# Step 5: Push to GitHub Pages
cd dist/<project-name>
git init
git remote add origin https://github.com/dice-group/Amharic_DBpedia_Chapter.git
git branch -M main
git add .
git commit -m "Deploy Amharic_DBpedia_Chapter to GitHub Pages"
git push -u origin main:gh-pages
